### PR TITLE
feat(ui): custom telescope picker with additonal features

### PR DESCRIPTION
**Pull request by mrjones2014**
Resolves: #236 

## How to Test

1. Please leave detailed testing instructions

## Testing for Regressions

I have tested the following:

- [ ] Triggering keymaps from `legendary.nvim` in all modes (normal, insert, visual)
- [ ] Creating keymaps via `legendary.nvim`, then triggering via the keymap in all modes (normal, insert, visual)
- [ ] Triggering commands from `legendary.nvim` in all modes (normal, insert, visual)
- [ ] Creating commands via `legendary.nvim`, then running the command manually from the command line
- [ ] `augroup`/`autocmd`s created through `legendary.nvim` work correctly

### CODE REVIEW

**Comment by mrjones2014** [comment]
So I've got the basics all done here but I'm trying to figure out how to implement the shortcuts thing. We would need to somehow pull the current sorted list state out of `telescope.actions.state`.

**Comment by mrjones2014** [comment]
Okay, figured that out. Now I need to figure out how I can label them. I had to go with `<S-1>` through `<S-0>` since `<C-1>` aren't send by terminals properly (you can't bind it in vim/neovim).

cc @olimorris

**Comment by mrjones2014** [comment]
Although, what if you want to type those characters 🤔 

that doesn't work.

**Comment by olimorris** [comment]
@mrjones2014 shall I give this branch a whirl?

**Comment by mrjones2014** [comment]
You can give it a test but I still need to tweak some things. The key bindings are currently `<S-1>` through `<S-0>` but those aren't good choices because that prevents you from actually typing a `!` through `)` lol.

I need to figure out what keymaps would work there, and how to label the items with the corresponding number. But currently pressing `!` should select the first item in the list, `@` the 2nd, `#` the 3rd, and so on. This works with a query typed and the list filtered too, just that the items are not labelled.

If you have any suggestions for better keymaps I'm all ears. `<C-1>` through `<C-0>` won't work because of the way terminals interpret those key presses, at least not without special terminal configuration. See: https://www.reddit.com/r/neovim/comments/iiqq1w/bind_cnumber/

**Comment by olimorris** [comment]
Yeah `<C-n>` was going to be my obvious solution but I love `<S-n>`. It's really obvious. The only downside would be if you're using a foreign keyboard layout.

As a back up solution, what about typing something like `@1` to select the first one and `@2` for the second? So even if I had typed `lsp` I could add `@2` to it (`lsp@2`) to select the second item?

**Comment by mrjones2014** [comment]
I don’t want to do anything that might interfere with a legitimate search term. That’s why I didn’t like `<S-1>` because because that’s a `!` character and you might want to actually type that.

that’s why I’m struggling a bit to think of a good set of keymaps.

**Comment by mrjones2014** [comment]
Circling back to this, we could possibly use `1-9` in normal mode only. Then the user could press `<Esc>1` or `<C-o>1` to select the first item.

**Pull request closed without merging**
