### PR TITLE
restore cursor position before executing the item

### LINKED ISSUE #76: Executing a command which requires the word under the cursor
Hey Mr Jones.

I have 75% converted all of my keymaps, commands and autocmds over to `legendary` now and I couldn't be happier. I've noticed a bit of an edge case regarding some complex mappings I have so thought I'd share as I couldn't find anything in the readme.

I have a nifty keymap which replaces the word under the cursor, across the whole of a buffer:
```lua
vim.api.nvim_set_keymap("n", "<LocalLeader>[", [[:%s/\<<C-r>=expand("<cword>")<CR>\>/]], {})
```

However when I try to incorporate into `legendary`, like so:
```lua
{ "<LocalLeader>[", [[:%s/\<<C-r>=expand("<cword>")<CR>\>/]], description = "Replace cursor words in file"},
```

I get the following error:
```lua
Error executing vim.schedule lua callback: ...k/packer/start/legendary.nvim/lua/legendary/executor.lua:44: Vim(substitute):E486: Pattern not found: \<^A8=expand("<cword>")^K\>
stack traceback:
    [C]: in function 'cmd'
    ...k/packer/start/legendary.nvim/lua/legendary/executor.lua:44: in function 'exec'
    ...k/packer/start/legendary.nvim/lua/legendary/executor.lua:74: in function 'try_execute'
    ...k/packer/start/legendary.nvim/lua/legendary/bindings.lua:264: in function  <...k/packer/start/legendary.nvim/lua/legendary/bindings.lua:263>
```

I'm guessing that as the cursor has focussed to legendary.nvim then executing `cword` yields nothing.

### PR DESCRIPTION
**Pull request by mrjones2014**
Fixes #76 

I believe this will fix your issue. I tested with some of the builtins like "Search word under cursor forward".

@olimorris can you test your keymapping on this branch?

### CODE REVIEW

**Comment by mrjones2014** [comment]
It looks like maybe it's evaluating `expand("<cword>")` literally or something.

**Comment by mrjones2014** [comment]
Wait @olimorris are you sure your mapping right-hand-side is correct? When I run that at the command line, not through legendary, I get the same error.

**Comment by mrjones2014** [comment]
Oh, I see the issue. Since it starts with a `:`, `legendary` is running it as a command, not as a keymap.

**Comment by mrjones2014** [comment]
@olimorris try now. I updated the executor to always use `nvim_feedkeys` over `nvim_command`.

**Comment by olimorris** [comment]
Works like a charm, thanks so much for fixing.

I'll likely have a few more edge cases to work through to so will raise any issues that I come across. Namely, some complex multiple cursor mappings 😵‍💫 . Based on your changes above, I think they may be a non issue.

**Comment by mrjones2014** [comment]
> multiple cursor mappings

Whaaat since when does Neovim have multiple cursors? Or are you using a plugin for it?

**Pull request merged**
