### PR TITLE
feat(api): Add command + API to repeat last selected item

### PR DESCRIPTION
**Pull request by mrjones2014**
Resolves: #384 

## How to Test

1. Run `legendary.nvim`'s finder UI and select a command
2. Call `:LegendaryRepeat` or `:lua require('legendary').repeat_previous()`
3. It should execute the last selected item again

## Testing for Regressions

I have tested the following:

- [x] Triggering keymaps from `legendary.nvim` in all modes (normal, insert, visual)
- [x] Creating keymaps via `legendary.nvim`, then triggering via the keymap in all modes (normal, insert, visual)
- [x] Triggering commands from `legendary.nvim` in all modes (normal, insert, visual)
- [x] Creating commands via `legendary.nvim`, then running the command manually from the command line
- [x] `augroup`/`autocmd`s created through `legendary.nvim` work correctly

### CODE REVIEW

**Comment by mrjones2014** [comment]
@notEvil mind giving it a test?

**Comment by notEvil** [comment]
It works. There is one problem though: the item could be invalid because the context changed (buffer, filter, ...).

**Comment by mrjones2014** [comment]
What do you mean? The context gets rebuilt when the item is re-executed. It will operate on the new context. Is that not what you were expecting?

**Comment by notEvil** [comment]
Sorry, I should pay more attention to terminology. With context I meant the state the repeat is initiated in. For instance, the last item could be available only for specific buffers or modes, or item filters could return false where they returned true previously.

**Comment by mrjones2014** [comment]
Ah, I see. I'll keep thinking on it.

**Comment by mrjones2014** [comment]
We'll probably need to keep track of the filters used on the last select and see if the item matches the filters as well.

**Comment by mrjones2014** [comment]
@notEvil I've pushed an update so that it only executes the item if it still matches the previous set of filters used.

You can escape this behavior by running the command with a bang, or passing `true` to the Lua function:

```vimL
:LegendaryRepeat
" ignore filters like
:LegendaryRepeat!
```

or in Lua

```lua
require('legendary').repeat_previous()
require('legendary').repeat_previous(--[[ ignore_filters: ]] true)
```

**Comment by notEvil** [comment]
I just tested it and it works as expected. Thanks!

**Comment by mrjones2014** [comment]
Thanks for helping me test!

**Pull request merged**
