### PR TITLE
feat(ui): Ability to filter keymaps by `filetype` and `buftype`

### PR DESCRIPTION
**Pull request by mrjones2014**
Resolves: #256

Implements filtering keymaps by filetype and buftype, as well as keymaps taking precedence based on specificity.

## How to Test

1. As an example, add a keymap like this: `{ '<C-v>', opts = { filetype = 'NvimTree' }, description = 'NvimTree: Open file in vertical split' }`
2. Add another keymap like this: `{ '<C-v>`, description = 'Notice this has the same keys as above' }`
3. Open legendary.nvim in a normal buffer
4. Search for `<C-v>`
5. The 2nd keymap you added should show up, the nvim-tree one should not
6. Open nvim-tree
7. Open legendary.nvim from the nvim-tree buffer
8. Search for `<C-v>`
9. The nvim-tree keymap should show up and the other one should not

## Testing for Regressions

I have tested the following:

- [x] Triggering keymaps from `legendary.nvim` in all modes (normal, insert, visual)
- [x] Creating keymaps via `legendary.nvim`, then triggering via the keymap in all modes (normal, insert, visual)
- [x] Triggering commands from `legendary.nvim` in all modes (normal, insert, visual)
- [x] Creating commands via `legendary.nvim`, then running the command manually from the command line
- [x] `augroup`/`autocmd`s created through `legendary.nvim` work correctly

### CODE REVIEW

**Comment by mrjones2014** [comment]
@olimorris mind giving this a whirl? This will be needed for some plugin integrations such as the nvim-tree integration. See:

- #183 
- https://github.com/nvim-tree/nvim-tree.lua/issues/1869

**Comment by olimorris** [comment]
Just tried this now and works brilliantly. This is going to be a super powerful addition.

I tried moving to [netrw](https://github.com/olimorris/dotfiles/commit/513cd3ae404cda9f7885204350767ef711f8533d) recently and had a tonne of filetype specific mappings that this would have been brilliant for.

**Comment by mrjones2014** [comment]
Yeah I'm not sure how I feel about the implementation. It works but there are definitely some rough edges:

- Only one keymap will _ever_ appear for a given set of keys
- The keymap resolution part requires multiple filter passes, which could be an issue on slower machines
- The `opts.filetype` and `opts.buftype` options may be a bit misleading as they _do not bind based on filetype/buftype,_ it _just filters in the UI_

**Comment by olimorris** [comment]
I've been playing with this quite a bit in the last couple of days and it's working like a charm. Admittedly only on one keymap but it's great!

What are your thoughts on this as a long term addition to the plugin?

**Comment by mrjones2014** [comment]
> What are your thoughts on this as a long term addition to the plugin?

I want to add it in some form but I don’t love the current implementation as it leaves some ambiguity.

will keep thinking on it.

**Comment by mrjones2014** [comment]
... circling back to this. I haven't had time to work on open source stuff lately.

I think I like the idea. However, I think it would be best if `opts.filetype` and `opts.buftype` actually _bound the keymaps conditionally_ based on those, e.g. using `autocmd BufEnter`. That would get rid of the ambiguity.

Then another big problem I have to solve is the fact that the current implementation requires multiple filter passes to resolve the filtered keymaps. That's not good.

I will probably end up making a new PR. I think I'll have some time this weekend.

**Comment by mrjones2014** [comment]
Closing in favor of #317

**Pull request closed without merging**
