### PR TITLE
Rewrite in Teal

### PR DESCRIPTION
**Pull request by mrjones2014**
Relates to #106, first step in getting better docs put together

Defines proper types for each table type using Teal

## Test the Following

- [ ] Triggering keymaps from `legendary.nvim` in all modes (normal, insert, visual)
- [ ] Creating keymaps via `legendary.nvim`, then triggering via the keymap in all modes (normal, insert, visual)
- [ ] Triggering commands from `legendary.nvim` in all modes (normal, insert, visual)
- [ ] Creating commands via `legendary.nvim`, then running the command manually from the command line
- [ ] `augroup`/`autocmd`s created through `legendary.nvim` work correctly

### CODE REVIEW

**Comment by mrjones2014** [comment]
@olimorris @tsyroid @hsheikhali1 This is gonna need some really thorough testing. If you're willing, install from this branch, and let me know if you run into any issues.

**Comment by mrjones2014** [comment]
I think builtins are getting registered twice or something?

**Comment by mrjones2014** [comment]
never mind. Fixed in latest commit.

**Comment by olimorris** [comment]
Would love to. Will give this a run tomorrow!

**Comment by tsyroid** [comment]
So far so good here; been kicking the tires for a few hours and nothing’s
fallen off.

I haven’t really applied my ‘destructive nature’ to it yet, but I plan to
do so after dinner.

The only complaint I have, so far, is it’s annoyingly fast ;-)

/tom

**Comment by olimorris** [comment]
Working like a charm for myself too. Also agree...feels sooooo fast. Is this in my mind?

**Comment by mrjones2014** [comment]
Hmm, I don't think these changes would really affect performance. Although it is possible that there were some bugs that are now fixed due to me fixing typing errors, now that I have static typing with Teal, so maybe that affected it.

**Comment by tsyroid** [comment]
That and the fact it’s now compiled, no?

**Comment by mrjones2014** [comment]
It’s compiled to Lua though

**Comment by mrjones2014** [comment]
Going to go ahead and merge this.

**Pull request merged**
