### PR TITLE
fix: Correctly fallback to another value when which-key group prefix is nil

### PR DESCRIPTION
**Pull request by mrjones2014**
Resolves: #314

### CODE REVIEW

**Comment by mrjones2014** [comment]
@rawhat does this fix the issue? I am not sure if this will still correctly process the groups, but I'm not sure if there's really a way to without any prefix, because there isn't anything to match on. 🤔

**Comment by rawhat** [comment]
Not super familiar with what the changes were here to groups, so I can't speak to how that plays out.  But it does fix my issue!  Thank you 😃

**Comment by mrjones2014** [comment]
Basically `which-key.nvim` group names are used to generate `legendary.nvim` item groups.

I think it will work if I use empty string as the index in this case, which I think might still generate groups properly.

**Comment by mrjones2014** [comment]
@rawhat can you check once more that the latest commit still fixes your issue?

**Comment by rawhat** [comment]
Thanks for the explanation, that makes sense.  And yep, still works perfectly! 🙏🏻

**Pull request merged**
