### PR TITLE
feat(sort): Sort by "frecency" if sqlite is available

### PR DESCRIPTION
**Pull request by mrjones2014**
Resolves: #235 

## How to Test

Update your config to include this new dependency (only required for frecency sorting): https://github.com/kkharji/sqlite.lua

e.g.

```lua
use { 'mrjones2014/legendary.nvim', requires = 'kkharji/sqlite.lua' }
```

1. Ensure that everything like item picking and execution still works
2. Test that items seem to be sorted by both frequency and recency of use
3. Test that items _within item groups_ are also sorted the same way

## Testing for Regressions

I have tested the following:

- [x] Triggering keymaps from `legendary.nvim` in all modes (normal, insert, visual)
- [x] Creating keymaps via `legendary.nvim`, then triggering via the keymap in all modes (normal, insert, visual)
- [x] Triggering commands from `legendary.nvim` in all modes (normal, insert, visual)
- [x] Creating commands via `legendary.nvim`, then running the command manually from the command line
- [x] `augroup`/`autocmd`s created through `legendary.nvim` work correctly

### CODE REVIEW

**Comment by mrjones2014** [comment]
@olimorris mind using this branch for a few days and letting me know what you think?

**Comment by mrjones2014** [comment]
The advantage of this is that it uses SQLite so it persists the sorting scores across Neovim sessions.

**Comment by olimorris** [comment]
@mrjones2014 any config changes I need to make? Can verify that everything still works as intended.

**Comment by mrjones2014** [comment]
oh, do you have this in your dressing.nvim config:

```lua
return {
  'stevearc/dressing.nvim',
  event = 'VimEnter',
  config = function()
    require('dressing').setup({
      select = {
        get_config = function(opts)
          opts = opts or {}
          local cfg = {
            telescope = {
              layout_config = {
                width = 120,
                height = 25,
              },
            },
          }
          if opts.kind == 'legendary.nvim' then
            cfg.telescope.sorter = require('telescope.sorters').fuzzy_with_index_bias({})
          end
          return cfg
        end,
      },
    })
  end,
}
```

**Comment by mrjones2014** [comment]
also FYI I just made logs go in reverse chronological order (so new entries will be at the top) and limit to 1K lines

**Comment by mrjones2014** [comment]
For me, looks like I'm getting duplicate entries somehow 🤔 

```lua
[Tue Dec  6 14:09:13 2022][legendary.nvim] Computed item scores: {
  ['":LegendaryEvalBuf Eval the whole buffer as Lua"'] = 20,
  ['"<F3> n Toggle left IDE panel"'] = 40,
  ['"<function> Copy current relative filepath to clipboard {}"'] = 10,
  ['"Workspace"'] = 50,
  ["':BindLspKeymaps Manually bind LSP keymaps in case they didn\\'t get bound'"] = 10,
  ["':Icons Find NerdFont icons'"] = 40,
  ["':LegendaryEvalBuf Eval the whole buffer as Lua'"] = 100,
  ["'<F3> n Toggle left IDE panel'"] = 10,
  ["'Search...'"] = 10,
  ["'Workspace'"] = 20,
  [":BindLspKeymaps Manually bind LSP keymaps in case they didn't get bound"] = 10,
  [":Format Format the current document with LSP"] = 10,
  LSP = 30,
  ["Search..."] = 20,
  Workspace = 50,
  ["fr n Resume last Telescope finder"] = 10
}
```

**Comment by mrjones2014** [comment]
Yeah, issue is I need a better/more consistent way to get IDs escaped properly for SQL.

**Comment by mrjones2014** [comment]
Okay, should be fixed now.

**Comment by olimorris** [comment]
Oh yeah now we're cooking! Working like a charm 🚀 !!

I notice within groups there is no sorting but guessing that's by design at present.

**Comment by mrjones2014** [comment]
Hmm, there should be sorting within groups. I’ll take a look at that tomorrow.

**Comment by olimorris** [comment]
Off topic: Is it possible to hide keymaps from the legendary picker? Reason I ask is that I like to define all of my keymaps in a single file and Legendary's api does it so beautifully. Also...if there was an `enabled` option for keymaps I could neatly prevent the double map issue with LSP keymaps.

**Comment by mrjones2014** [comment]
Figured out why item groups were not being sorted. That should be fixed.

**Comment by olimorris** [comment]
Yep can confirm it's working perfectly.

Only thing I've spotted is when I run `:LegendaryFrecencyReset` and try and open Legendary again, I get the following:

```text
E5108: Error executing lua: .../site/pack/packer/start/sqlite.lua/lua/sqlite/assert.lua:28: sqlite.lua: can not execute select, item_count doesn't exists.
stack traceback:
        [C]: in function 'assert'
        .../site/pack/packer/start/sqlite.lua/lua/sqlite/assert.lua:28: in function 'is_sqltbl'
        ...nvim/site/pack/packer/start/sqlite.lua/lua/sqlite/db.lua:596: in function 'func'
        ...nvim/site/pack/packer/start/sqlite.lua/lua/sqlite/db.lua:218: in function 'transaction'
        ...acker/opt/legendary.nvim/lua/legendary/api/db/client.lua:63: in function 'get_item_scores'
        ...acker/opt/legendary.nvim/lua/legendary/data/itemlist.lua:117: in function 'sort_inplace'
        ...pack/packer/opt/legendary.nvim/lua/legendary/ui/init.lua:56: in function 'select_inner'
        ...pack/packer/opt/legendary.nvim/lua/legendary/ui/init.lua:95: in function 'select'
        ...te/pack/packer/opt/legendary.nvim/lua/legendary/init.lua:112: in function <...te/pack/packer/opt/legendary.nvim/lua/legendary/init.lua:110>
```

**Comment by olimorris** [comment]
> Currently the only way is just to not provide a description, however if you want an option to keep the description and still not show it in the picker, it would be really easy to implement, if you wanna make a PR. Or I can do it this week some time.

I'll have a bash at a PR actually. About time I became more familiar with this code base. Under no obligation to accept it of course!

**Comment by mrjones2014** [comment]
> Yep can confirm it's working perfectly.
> 
> One thing I've spotted is when I run `:LegendaryFrecencyReset` and try and open Legendary again, I get the following:
> 
> ```
> E5108: Error executing lua: .../site/pack/packer/start/sqlite.lua/lua/sqlite/assert.lua:28: sqlite.lua: can not execute select, item_count doesn't exists.
> stack traceback:
>         [C]: in function 'assert'
>         .../site/pack/packer/start/sqlite.lua/lua/sqlite/assert.lua:28: in function 'is_sqltbl'
>         ...nvim/site/pack/packer/start/sqlite.lua/lua/sqlite/db.lua:596: in function 'func'
>         ...nvim/site/pack/packer/start/sqlite.lua/lua/sqlite/db.lua:218: in function 'transaction'
>         ...acker/opt/legendary.nvim/lua/legendary/api/db/client.lua:63: in function 'get_item_scores'
>         ...acker/opt/legendary.nvim/lua/legendary/data/itemlist.lua:117: in function 'sort_inplace'
>         ...pack/packer/opt/legendary.nvim/lua/legendary/ui/init.lua:56: in function 'select_inner'
>         ...pack/packer/opt/legendary.nvim/lua/legendary/ui/init.lua:95: in function 'select'
>         ...te/pack/packer/opt/legendary.nvim/lua/legendary/init.lua:112: in function <...te/pack/packer/opt/legendary.nvim/lua/legendary/init.lua:110>
> ```
> 
> A quick restart of Neovim and everything is fine.

Ah, yeah I think I know the issue. That command just deletes the database file, I need to re-bootstrap it afterwards.

**Comment by olimorris** [comment]
> OOOOOH @olimorris I just had an idea!
> 
> What if we wrap your implementations of your keymaps and commands and functions and autocmds in a wrapper function, that updates the frecency score when you use the item, even if you triggered it manually and not through the finder?
> 
> This would probably be a behavior you could turn off in the config.

Interesting idea. It crossed my mind earlier actually. My argument against it is if I am using keymaps/commands without Legendary, then when I do reach for Legendary, it's likely for a command/keymap that's too long to type or I can't remember. They're the ones I'd want to be ranked higher

**Comment by mrjones2014** [comment]
Yeah, had that thought as well. I think I'll leave it out, but I won't rule it out as a possible option for the future.

**Comment by olimorris** [comment]
Also congrats on merging this. It's an epic PR

**Comment by mrjones2014** [comment]
> Yeah it's still a really neat idea.
> 
> I meant to ask, if I remap a keymap, how does Legendary handle that wrt frecency?

It will change the items unique ID and therefore reset the recency. Maybe it shouldn't if only the key changed though 🤔 
Feel free to open an issue and we can think about that some more.

**Pull request merged**
