### PR TITLE
let which-key handle key binding if which-key integration is used

### PR DESCRIPTION
**Pull request by mrjones2014**
Resolves: #[issue number] 

## How to Test

1. Please leave detailed testing instructions

## Testing for Regressions

I have tested the following:

- [ ] Triggering keymaps from `legendary.nvim` in all modes (normal, insert, visual)
- [ ] Creating keymaps via `legendary.nvim`, then triggering via the keymap in all modes (normal, insert, visual)
- [ ] Triggering commands from `legendary.nvim` in all modes (normal, insert, visual)
- [ ] Creating commands via `legendary.nvim`, then running the command manually from the command line
- [ ] `augroup`/`autocmd`s created through `legendary.nvim` work correctly

### CODE REVIEW

**Comment by mrjones2014** [comment]
@bennypowers you use which-key right? Would you mind testing this out? 

Original purpose was for something else but I think it’s a good improvement regardless. Removes some redundant mapping.

**Comment by bennypowers** [comment]
how would this affect my [config](https://github.com/bennypowers/dotfiles/blob/master/.config/nvim/lua/config/which-key.lua)?

**Comment by bennypowers** [comment]
I poked around for a few minutes and both legendary menu and which-key bindings seem to work fine

**Comment by mrjones2014** [comment]
Thanks for testing! I’ll get this merged soon then.

**Comment by mrjones2014** [comment]
@bennypowers I made a few changes, can you test one more time?

**Comment by bennypowers** [comment]
yeah looks ok. I didn't do exhaustive testing, but I did confirm that at least one or two of the bindings that I set up in my which-key config file appeared in both places

**Comment by mrjones2014** [comment]
Awesome, that's all that this PR should really affect. Going to merge. Thanks!

**Pull request merged**
