### PR TITLE
Custom sorting

### PR DESCRIPTION
**Pull request by mrjones2014**
Resolves: #218 

## How to Test

Excerpt from `config.lua` updates:

```lua
  -- Options for list sorting. Note that fuzzy-finders will still
  -- do their own sorting. For telescope.nvim, you can set it to use
  -- `require('telescope.sorters').fuzzy_with_index_bias({})` when
  -- triggered via `legendary.nvim`. Example config for `dressing.nvim`:
  --
  -- require('dressing').setup({
  --  select = {
  --    get_config = function(opts)
  --      if opts.kind == 'legendary.nvim' then
  --        return {
  --          telescope = {
  --            sorter = require('telescope.sorters').fuzzy_with_index_bias({})
  --          }
  --        }
  --      else
  --        return {}
  --      end
  --    end
  --  }
  -- })
  sort = {
    -- sort most recently used item to the top
    most_recent_first = true,
    -- sort user-defined items before built-in items
    user_items_first = true,
    -- sort the specified item type before other item types,
    -- value must be one of: 'keymap', 'command', 'autocmd', nil
    item_type_bias = nil,
  }
```

So, set up legendary like:

```lua
require('legendary').setup({
  sort = {
    most_recent_first = true,
    user_items_first = true,
    item_type_bias = 'command',
  }
})
```

Then set up `dressing.nvim` as shown in the comment above.

Then, items should be sorted by:

- most recent item first
- user-defined items before built-ins
- commands before other item types

## Testing for Regressions

I have tested the following:

- [ ] Triggering keymaps from `legendary.nvim` in all modes (normal, insert, visual)
- [ ] Creating keymaps via `legendary.nvim`, then triggering via the keymap in all modes (normal, insert, visual)
- [ ] Triggering commands from `legendary.nvim` in all modes (normal, insert, visual)
- [ ] Creating commands via `legendary.nvim`, then running the command manually from the command line
- [ ] `augroup`/`autocmd`s created through `legendary.nvim` work correctly

### CODE REVIEW

**Comment by mrjones2014** [comment]
@olimorris the implementation is kinda hacky (basically, sorts the list upfront, then uses `fuzzy_with_index_bias` sorter: https://github.com/nvim-telescope/telescope.nvim#sorters) but thoughts on this?

**Comment by olimorris** [comment]
Brilliant and works as expected:

Screen Shot 2022-11-16 at 20 16 17@2x

The question to yourself...is it going to be a nightmare to maintain? It adds value to myself but perhaps not many others.

Btw...when I add `item_type_bias = "keymap"`, I get the same order when I search for `comm` as I do with `item_type_bias = "command"`

**Comment by mrjones2014** [comment]
>The question to yourself...is it going to be a nightmare to maintain? It adds value to myself but perhaps not many others.

The logic itself isn't too bad. There's no way to make it not require user config though, and currently it's telescope-specific.

>Btw...when I add item_type_bias = "keymap", I get the same order when I search for comm as I do with item_type_bias = "command"

Yeah I'm sure it's buggy at the moment. I'm trying to figure out the best way to sort without having to do multiple passes.

**Comment by mrjones2014** [comment]
@olimorris I took a new approach that I think works a little better -- We just keep the item list always sorted, then suggest using `require('telescope.sorters').fuzzy_with_index_bias({})` for the `legendary.nvim` sorter. Let me know how this works for you. It's more stable and not necessarily telescope-specific (other fuzzy finders could have a sorter that has an index bias as well).

**Comment by mrjones2014** [comment]
I updated the original PR comment with how to configure it with the new approach.

**Comment by mrjones2014** [comment]
I've been busy with work, not sure when I'll have time to finalize this, but have the changes been working out for you @olimorris ?

**Comment by mrjones2014** [comment]
@olimorris had a chance to take another look at this?

**Comment by mrjones2014** [comment]
Going to merge this. We can iterate on it further if needed.

**Pull request merged**
