### PR TITLE
rewrite README.md

### LINKED ISSUE #28: Revamped documentation
The README.md is getting quite big. We should break it down into either separate files or better organized sections.

We should have a section explaining in detail the required table structures for each type:

 - keymaps
 - commands
 - augroups
 - autocmds
 
And then a section on the Lua API functions, how/when to use them vs. using `require('legendary').setup()` etc.

### PR DESCRIPTION
**Pull request by mrjones2014**
Resolves #28

### CODE REVIEW

**Comment by mrjones2014** [comment]
@tsyroid I took a first pass at re-writing the README.md. Let me know what you think. It can be previewed in it's GitHub rendered form here: https://github.com/mrjones2014/legendary.nvim/tree/matjones/28-docs-revamp

**Comment by mrjones2014** [comment]
Can't decide how I feel about the header thing I made. Should we go back to just a normal markdown heading?

```md
# 🗺️ `legendary.nvim`
```

**Comment by tsyroid** [comment]
Sorry. Did I poop on your parade? ;-)

**Comment by mrjones2014** [comment]
haha no I was just done for the evening.

I don't think I like the ASCII graphic thing after sleeping on it. like you said it's not very clear.

I do kinda like the `<details>` markup since it creates collapsible sections on GitHub. Another option would be to split the table structure section into a new file, but I need to make sure `panvimdoc` can generate the vim docs from multiple source files.

**Pull request merged**
