### PR TITLE
draft: Plugin integrations!

### PR DESCRIPTION
**Pull request by mrjones2014**
Resolves: #183 

## How to Test

1. Install the Neovim plugins listed in the README.md changes (links in the table lower down in the README.md)
2. Enable the plugins as shown in the changes to the config section of README.md
3. Trigger the legendary.nvim finder window
4. You should be able to find keymaps/commands/functions from the Neovim plugins you just installed, automatically, without you adding them manually

## Testing for Regressions

I have tested the following:

- [x] Triggering keymaps from `legendary.nvim` in all modes (normal, insert, visual)
- [x] Creating keymaps via `legendary.nvim`, then triggering via the keymap in all modes (normal, insert, visual)
- [x] Triggering commands from `legendary.nvim` in all modes (normal, insert, visual)
- [x] Creating commands via `legendary.nvim`, then running the command manually from the command line
- [x] `augroup`/`autocmd`s created through `legendary.nvim` work correctly

### CODE REVIEW

**Comment by mrjones2014** [comment]
@olimorris sorry to bug you out of the blue but this is just an idea I'm experimenting with. If you have a moment, could you give me some initial feedback on the implementation here? Specifically the architecture and the code itself.

You can ignore all the `*.lua` files since they are generated from the Teal (`*.tl`) sources, just look at those for code review. It should be similar enough to Lua that you should have no problem understanding it.

The idea is to have a system where legendary.nvim can automatically load commands and mappings from other plugins.

**Comment by olimorris** [comment]
Absolutely will! Give me the weekend and i'll feedback. Legendary is such a core part of my workflow

**Comment by mrjones2014** [comment]
Let me know if there's any additional plugins you'd like included in the first batch 🙂 

I think this seems to work pretty well.

**Comment by olimorris** [comment]
Just gave this a whirl now for OneDarkPro. It just works. Really, really nice!

Would I use this feature? For sure! I guess my big question is how you can easily override the default mappings for a plugin or is this for commands only?

**Comment by mrjones2014** [comment]
> how you can easily override the default mappings for a plugin or is this for commands only?

Hmm, yeah my first pass here is only listing them, but being able to manage all keymaps in the same place would be great too.

I think I’ll change the approach a bit. Stay tuned.

**Comment by mrjones2014** [comment]
So, very much an experiment still, but I'm thinking of a system like this:

- Register your plugin keymaps with legendary.nvim (I'll ask a question about the best way to do this below)
- Then use the legendary.nvim keymaps for the plugin like so:

```lua
require('someplugin').setup(require('legendary').plugin('someplugin', {
  -- the rest of your plugin config here,
  -- legendary.nvim will merge your config
  -- with the keymaps config set up via the
  -- legendary.nvim plugin API
}))
```

Now, the question of the best API for setting up the keymaps with legendary.nvim, I have a few ideas, @olimorris let me know which you think is best or which will be most flexible and work best with people's workflows/configs:

**Option 1:** Using a new key on legendary tables

```lua
require('legendary').setup({
  keymaps = {
    -- your other legendary.nvim keymaps here
    { '<leader>co', require('someplugin').some_action, description = 'Some plugin action', plugin = 'someplugin' },
  }
})
```

**Option 2:** Using a separate entry type (slightly less complex to implement but not by a lot)
```lua
require('legendary').setup({
  keymaps = {}, -- your other keymaps here
  plugins = {
    someplugin = {
        { '<leader>co', require('someplugin').some_action, description = 'Some plugin action' },
    }
  }
})
-- would also come with a corresponding API function, though they'd all have to be
-- registered with legendary.nvim before configuring 'someplugin'
require('legendary').bind_plugin_keymap( { 
  '<leader>co',
  require('someplugin').some_action,
  description = 'Some plugin action',
 })
```

**Option 3:** something else I haven't thought of?

**Comment by mrjones2014** [comment]
Hmm, this doesn't cover the case of conditional mappings (e.g. mappings for a specific buffer, for example op.nvim's sidebar mappings are only active if the current buffer is the sidebar).

I'll need to think about the plugin API a bit more. The question from last comment still stands though.

**Comment by mrjones2014** [comment]
I think we would need to have the user pass the keymap config path that the external plugin uses, so for example for `op.nvim` it would need to look something like:

```lua
require('legendary').setup({
  keymaps = {}, -- your other keymaps here
  plugins = {
    op = {
      sidebar = {
        {  '<CR>', 'default_open', description = 'Open 1Password item with default handler' },
      }
    }
  }
})
```

**Comment by mrjones2014** [comment]
Hm, I don't think this covers all cases either. Not sure how to approach this. 🤔

**Comment by olimorris** [comment]
From a pure user API perspective, I'd love to be able to do something like this:

```lua
require('legendary').setup({
  plugins = {
    onedarkpro = {
      keymaps = {
        {  'OnedarkproCache', '<leader>cc' }, -- Move the Onedarkpro cache keymap to leader cc
      },
    },
  },
})
```
So say within the Onedarkpro plugin file, I have all of the default mappings defined; overwriting them would be a easy as calling the mapping name and specifying the new mapping. I'll have a think on this too.

**Comment by mrjones2014** [comment]
You could already do that with normal `legendary.nvim` keymappings though, right?

What I'm moreso aiming to do with this feature is to handle the keymaps of other Neovim plugins that _set their own keymaps,_ for example `diffview.nvim` has configuration options to set up keymaps in the diff view, I'd like to be able to manage those keymaps in `legendary.nvim` despite them being managed/wired up by `diffview.nvim`.

Turns out this is an extremely difficult problem to solve in a generic way, especially considering that those keymaps are only active when diff view is open, so we'd need to introduce an extra layer of item filtering.

That being said, I'm not sure where to go with this PR 🤔 

I'll leave it open for community comments in case anyone has any ideas.

**Comment by olimorris** [comment]
> You could already do that with normal `legendary.nvim` keymappings though, right?

You could, but then I have to create the mapping myself in my own legendary config rather than just overwrite it in the `setup` call. Plus, if the plugin author changes a command, he can make that change in the legendary plugin file, keeping the name the same, and I don't need to touch anything config-wise.

**Comment by mrjones2014** [comment]
Closing since this won’t be compatible with v2

**Pull request closed without merging**
