### PR TITLE
feat(which-key): Add option to not group items when parsing which-key.…

### PR DESCRIPTION
**Pull request by mrjones2014**
…nvim tbls

Resolves: #372 

## How to Test

1. Have which-key config with groups
2. Enable which-key integration
3. `require('legendary').setup({ which_key = {  use_groups = false  } })`
4. legendary.nvim should not create item groups from the which-key groups

## Testing for Regressions

I have tested the following:

- [x] Triggering keymaps from `legendary.nvim` in all modes (normal, insert, visual)
- [x] Creating keymaps via `legendary.nvim`, then triggering via the keymap in all modes (normal, insert, visual)
- [x] Triggering commands from `legendary.nvim` in all modes (normal, insert, visual)
- [x] Creating commands via `legendary.nvim`, then running the command manually from the command line
- [x] `augroup`/`autocmd`s created through `legendary.nvim` work correctly

### CODE REVIEW

**Comment by mrjones2014** [comment]
@PetitBandit mind giving this a test? You should be able to just set `branch = 'mrj/372/whichkey-group-optional'` on your plugin manager where you install the plugin.

**Comment by PetitBandit** [comment]
I just tried it and i still get the groupname showing up and not the label of the command inside the groups.
this exemple:
 ```
 y = {
    name = "config+", -- optional group name
    c = { "<cmd>lua require('plugins.telescope').search_color()<cr>", "colorscheme"}, 
    h = { ":CccHighlighterToggle<CR>", "highlight colors"}, 
    o = { 
      name = "options", 
         b = { "background" }, -- just a label. don't create any mapping
         h = { "hard times" }, 
         r = { "relative number" },
         w = { "wrap" }, 
    },
    p = {
      name = "plugins",
         i = { ":PlugInstall<cr>", "Install plugins"}, 
         c = { ":PlugClean<cr>", "clean plugins"}, 
         u = { ":PlugUpdate<cr>", "update plugins"}, 
    }
  },
```
in this exemple if i searched background in legendary it wouldnt show up, but configs (name of the group) would

**Comment by mrjones2014** [comment]
Did you set the new `config.which_key.use_groups = false` option? it is `true` by default, you will need to change it to disable grouping. It works for me when I copy your table:

image

**Comment by PetitBandit** [comment]
Works flawlessly, thank you so much 🔥

**Pull request merged**
